kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-dynamic-volume-claim
spec:
  storageClassName: "lsc-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi